plugins:
    - jekyll-feed
    - jekyll-tagging-related_posts
    - jekyll-mentions
    - jekyll-compose
    - jekyll-redirect-from
    - jekyll-seo-tag # Add for better SEO
    - jekyll-minifier

incremental: true
sass:
  style: compressed
defaults:
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
          robots: 'index, follow'

header_pages:
    - index.md
    - pages/search.md
    - pages/files.md
    - pages/about.md
    - index.md
    - pages/bookmarks.md
    - pages/files.md
    - pages/about.md

include:
    - 'files'

exclude:
    - 'update.sh'
    - 'jekyll-theme-console.gemspec'
    - 'Rakefile'
    - 'vendor/bundle'

footer:
    - 'follow on <a href="https://twitter.com/0x7C2f">Twitter</a>'
    - '|'
    - '<a href="feed.xml">RSS Feed</a>'
    - '|'
    - '<a href="https://0x7c2f.github.io/startpage/">Startpage</a>'
